#!/bin/bash
# Quick Development Commands Reference
# RPI Communication App

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  RPI Communication App - Development Quick Reference          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📱 MOBILE APP (Flutter)"
echo "─────────────────────────────────────────────────────────"
echo "  cd /workspaces/college-communication-app/apps/mobile"
echo ""
echo "  flutter run -d linux          # Run on Linux desktop"
echo "  flutter build apk --debug     # Build debug APK"
echo "  flutter build apk --release   # Build release APK"
echo "  flutter test                  # Run tests"
echo "  flutter analyze               # Code analysis"
echo "  flutter clean                 # Clean build cache"
echo "  flutter pub get               # Install dependencies"
echo "  flutter pub outdated          # Check outdated packages"
echo ""

echo "🌐 WEB DASHBOARD (React + Vite)"
echo "─────────────────────────────────────────────────────────"
echo "  cd /workspaces/college-communication-app/apps/web"
echo ""
echo "  npm run dev                   # Start dev server (port 5173)"
echo "  npm run build                 # Build for production"
echo "  npm run preview               # Preview production build"
echo "  npm run lint                  # TypeScript type check"
echo "  npm install                   # Install dependencies"
echo ""

echo "🔧 DEVELOPMENT TOOLS"
echo "─────────────────────────────────────────────────────────"
echo "  flutter doctor                # Check Flutter setup"
echo "  flutter doctor -v             # Detailed status"
echo "  dart format .                 # Format Dart code"
echo "  git status                    # Check git status"
echo "  git pull --rebase             # Update from remote"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "─────────────────────────────────────────────────────────"
echo "  # Flutter issues"
echo "  flutter clean && flutter pub get"
echo ""
echo "  # Web issues"
echo "  cd apps/web && rm -rf node_modules && npm install"
echo ""
echo "  # Port conflict"
echo "  lsof -ti:5173 | xargs kill -9"
echo ""

echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────────────────────"
echo "  cat README.md                           # Project overview"
echo "  cat DEV_ENVIRONMENT_READY.md            # Environment status"
echo "  cat docs/QUICK_START.md                 # Quick start guide"
echo "  cat docs/APPWRITE_GUIDE.md              # Appwrite setup"
echo "  cat PRODUCTION_DEPLOYMENT_GUIDE.md      # Deployment"
echo ""

echo "🚀 QUICK START"
echo "─────────────────────────────────────────────────────────"
echo "  # Terminal 1: Mobile App"
echo "  cd /workspaces/college-communication-app/apps/mobile"
echo "  flutter run -d linux"
echo ""
echo "  # Terminal 2: Web Dashboard"
echo "  cd /workspaces/college-communication-app/apps/web"
echo "  npm run dev"
echo ""

echo "✅ ENVIRONMENT STATUS"
echo "─────────────────────────────────────────────────────────"
echo "  Flutter:   $(flutter --version 2>&1 | head -1 | cut -d' ' -f2)"
echo "  Dart:      $(dart --version 2>&1 | cut -d' ' -f4)"
echo "  Node.js:   $(node --version)"
echo "  Java:      $(java -version 2>&1 | head -1 | cut -d'"' -f2)"
echo "  Git:       $(git --version | cut -d' ' -f3)"
echo ""

echo "💡 TIP: Run this script anytime with: ./dev-quick-ref.sh"
echo ""
