/**
 * Teachers Page
 * Manage teacher profiles with dedicated teacher-specific fields
 */

import React, { useState, useEffect } from 'react';
import {
  Container,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
  Button,
  Box,
  Chip,
  CircularProgress,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Tooltip,
    Grid,
  Autocomplete,
} from '@mui/material';
import {
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Search as SearchIcon,
  Email as EmailIcon,
  Phone as PhoneIcon,
  Room as RoomIcon,
} from '@mui/icons-material';
import { teacherService, Teacher, TeacherFormData } from '../services/teacher.service';
import Snackbar from '../components/Snackbar';
import { isValidEmail, isRequired } from '../utils/validation';

const TeachersPage: React.FC = () => {
  const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [filteredTeachers, setFilteredTeachers] = useState<Teacher[]>([]);
  const [loading, setLoading] = useState(true);
  const [openDialog, setOpenDialog] = useState(false);
  const [editingTeacher, setEditingTeacher] = useState<Teacher | null>(null);
  const [formData, setFormData] = useState<TeacherFormData>({
    user_id: '',
    email: '',
    full_name: '',
    department: '',
    is_active: true,
  });
  const [searchTerm, setSearchTerm] = useState('');
  const [filterDept, setFilterDept] = useState<string>('all');
  const [departments, setDepartments] = useState<string[]>([]);
  const [snackbar, setSnackbar] = useState({
    open: false,
    message: '',
    severity: 'success' as 'success' | 'error' | 'info' | 'warning',
  });

  useEffect(() => {
    loadTeachers();
    loadDepartments();
  }, []);

  useEffect(() => {
    // Filter teachers based on search term and department filter
    let filtered = teachers;

    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      filtered = filtered.filter(
        (teacher) =>
          teacher.full_name.toLowerCase().includes(term) ||
          teacher.email.toLowerCase().includes(term) ||
          teacher.employee_id?.toLowerCase().includes(term) ||
          teacher.department.toLowerCase().includes(term) ||
          teacher.designation?.toLowerCase().includes(term)
      );
    }

    if (filterDept !== 'all') {
      filtered = filtered.filter((teacher) => teacher.department === filterDept);
    }

    setFilteredTeachers(filtered);
  }, [searchTerm, filterDept, teachers]);

  const loadTeachers = async () => {
    try {
      const data = await teacherService.getTeachers();
      setTeachers(data);
      setFilteredTeachers(data);
    } catch (error) {
      console.error('Error loading teachers:', error);
      showSnackbar('Failed to load teachers', 'error');
    } finally {
      setLoading(false);
    }
  };

  const loadDepartments = async () => {
    try {
      const depts = await teacherService.getDepartments();
      setDepartments(depts);
    } catch (error) {
      console.error('Error loading departments:', error);
    }
  };

  const showSnackbar = (
    message: string,
    severity: 'success' | 'error' | 'info' | 'warning' = 'success'
  ) => {
    setSnackbar({ open: true, message, severity });
  };

  const handleOpenDialog = (teacher?: Teacher) => {
    if (teacher) {
      setEditingTeacher(teacher);
      setFormData({
        user_id: teacher.user_id,
        email: teacher.email,
        full_name: teacher.full_name,
        employee_id: teacher.employee_id,
        department: teacher.department,
        designation: teacher.designation,
        subjects: teacher.subjects,
        qualification: teacher.qualification,
        specialization: teacher.specialization,
        phone_number: teacher.phone_number,
        office_room: teacher.office_room,
        office_hours: teacher.office_hours,
        joining_date: teacher.joining_date,
        photo_url: teacher.photo_url,
        bio: teacher.bio,
        is_active: teacher.is_active,
      });
    } else {
      setEditingTeacher(null);
      setFormData({
        user_id: 'unique()', // Will be generated by Appwrite
        email: '',
        full_name: '',
        department: '',
        is_active: true,
      });
    }
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
    setEditingTeacher(null);
  };

  const handleSave = async () => {
    // Validate required fields
    if (!isRequired(formData.full_name)) {
      showSnackbar('Full name is required', 'error');
      return;
    }
    if (!isRequired(formData.email)) {
      showSnackbar('Email is required', 'error');
      return;
    }
    if (!isValidEmail(formData.email)) {
      showSnackbar('Please enter a valid email address', 'error');
      return;
    }
    if (!isRequired(formData.department)) {
      showSnackbar('Department is required', 'error');
      return;
    }

    try {
      if (editingTeacher) {
        await teacherService.updateTeacher(editingTeacher.$id, formData);
        showSnackbar('Teacher updated successfully', 'success');
      } else {
        await teacherService.createTeacher(formData);
        showSnackbar('Teacher created successfully', 'success');
      }
      handleCloseDialog();
      loadTeachers();
      loadDepartments(); // Refresh departments list
    } catch (error: unknown) {
      console.error('Error saving teacher:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      showSnackbar(
        `Failed to ${editingTeacher ? 'update' : 'create'} teacher: ${errorMessage}`,
        'error'
      );
    }
  };

  const handleDelete = async (teacherId: string) => {
    if (window.confirm('Are you sure you want to delete this teacher?')) {
      try {
        await teacherService.deleteTeacher(teacherId);
        showSnackbar('Teacher deleted successfully', 'success');
        loadTeachers();
      } catch (error) {
        console.error('Error deleting teacher:', error);
        showSnackbar('Failed to delete teacher', 'error');
      }
    }
  };

  const handleToggleActive = async (teacher: Teacher) => {
    try {
      await teacherService.toggleTeacherStatus(teacher.$id);
      showSnackbar(
        `Teacher ${!teacher.is_active ? 'activated' : 'deactivated'} successfully`,
        'success'
      );
      loadTeachers();
    } catch (error) {
      console.error('Error toggling teacher status:', error);
      showSnackbar('Failed to update teacher status', 'error');
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4" component="h1">
          👨‍🏫 Teachers Management
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => handleOpenDialog()}
        >
          Add Teacher
        </Button>
      </Box>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <Grid container spacing={2} alignItems="center">
          <Grid item xs={12} md={6}>
            <TextField
              fullWidth
              size="small"
              placeholder="Search by name, email, employee ID, designation..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: <SearchIcon sx={{ mr: 1, color: 'text.secondary' }} />,
              }}
            />
          </Grid>
          <Grid item xs={12} md={3}>
            <FormControl fullWidth size="small">
              <InputLabel>Department</InputLabel>
              <Select
                value={filterDept}
                label="Department"
                onChange={(e) => setFilterDept(e.target.value)}
              >
                <MenuItem value="all">All Departments</MenuItem>
                {departments.map((dept) => (
                  <MenuItem key={dept} value={dept}>
                    {dept}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} md={3}>
            <Typography variant="body2" color="text.secondary">
              Total: {filteredTeachers.length} teacher(s)
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      {/* Teachers Table */}
      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Name</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Department</TableCell>
              <TableCell>Designation</TableCell>
              <TableCell>Subjects</TableCell>
              <TableCell>Contact</TableCell>
              <TableCell>Status</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {filteredTeachers.length === 0 ? (
              <TableRow>
                <TableCell colSpan={8} align="center">
                  <Typography variant="body2" color="text.secondary" py={4}>
                    {searchTerm || filterDept !== 'all'
                      ? 'No teachers found matching your filters'
                      : 'No teachers yet. Click "Add Teacher" to create one.'}
                  </Typography>
                </TableCell>
              </TableRow>
            ) : (
              filteredTeachers.map((teacher) => (
                <TableRow key={teacher.$id} hover>
                  <TableCell>
                    <Box>
                      <Typography variant="body2" fontWeight="medium">
                        {teacher.full_name}
                      </Typography>
                      {teacher.employee_id && (
                        <Typography variant="caption" color="text.secondary">
                          ID: {teacher.employee_id}
                        </Typography>
                      )}
                    </Box>
                  </TableCell>
                  <TableCell>
                    <Tooltip title={teacher.email}>
                      <Box display="flex" alignItems="center" gap={0.5}>
                        <EmailIcon fontSize="small" color="action" />
                        <Typography variant="body2" noWrap sx={{ maxWidth: 150 }}>
                          {teacher.email}
                        </Typography>
                      </Box>
                    </Tooltip>
                  </TableCell>
                  <TableCell>
                    <Chip label={teacher.department} size="small" color="primary" variant="outlined" />
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">
                      {teacher.designation || '-'}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    {teacher.subjects && teacher.subjects.length > 0 ? (
                      <Box display="flex" gap={0.5} flexWrap="wrap">
                        {teacher.subjects.slice(0, 2).map((subject, idx) => (
                          <Chip key={idx} label={subject} size="small" />
                        ))}
                        {teacher.subjects.length > 2 && (
                          <Chip label={`+${teacher.subjects.length - 2}`} size="small" color="default" />
                        )}
                      </Box>
                    ) : (
                      <Typography variant="body2" color="text.secondary">-</Typography>
                    )}
                  </TableCell>
                  <TableCell>
                    <Box>
                      {teacher.phone_number && (
                        <Box display="flex" alignItems="center" gap={0.5} mb={0.5}>
                          <PhoneIcon fontSize="small" color="action" />
                          <Typography variant="caption">{teacher.phone_number}</Typography>
                        </Box>
                      )}
                      {teacher.office_room && (
                        <Box display="flex" alignItems="center" gap={0.5}>
                          <RoomIcon fontSize="small" color="action" />
                          <Typography variant="caption">{teacher.office_room}</Typography>
                        </Box>
                      )}
                      {!teacher.phone_number && !teacher.office_room && (
                        <Typography variant="body2" color="text.secondary">-</Typography>
                      )}
                    </Box>
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={teacher.is_active ? 'Active' : 'Inactive'}
                      color={teacher.is_active ? 'success' : 'default'}
                      size="small"
                      onClick={() => handleToggleActive(teacher)}
                      sx={{ cursor: 'pointer' }}
                    />
                  </TableCell>
                  <TableCell align="right">
                    <Tooltip title="Edit">
                      <IconButton
                        size="small"
                        onClick={() => handleOpenDialog(teacher)}
                        color="primary"
                      >
                        <EditIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                    <Tooltip title="Delete">
                      <IconButton
                        size="small"
                        onClick={() => handleDelete(teacher.$id)}
                        color="error"
                      >
                        <DeleteIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </TableContainer>

      {/* Add/Edit Dialog */}
      <Dialog open={openDialog} onClose={handleCloseDialog} maxWidth="md" fullWidth>
        <DialogTitle>
          {editingTeacher ? 'Edit Teacher' : 'Add New Teacher'}
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            {/* Personal Information */}
            <Grid item xs={12}>
              <Typography variant="subtitle2" color="primary" gutterBottom>
                Personal Information
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Full Name"
                required
                value={formData.full_name}
                onChange={(e) => setFormData({ ...formData, full_name: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Email"
                type="email"
                required
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Employee ID"
                value={formData.employee_id || ''}
                onChange={(e) => setFormData({ ...formData, employee_id: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Phone Number"
                value={formData.phone_number || ''}
                onChange={(e) => setFormData({ ...formData, phone_number: e.target.value })}
              />
            </Grid>

            {/* Academic Information */}
            <Grid item xs={12}>
              <Typography variant="subtitle2" color="primary" gutterBottom sx={{ mt: 2 }}>
                Academic Information
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <Autocomplete
                freeSolo
                options={departments}
                value={formData.department}
                onChange={(_, newValue) => setFormData({ ...formData, department: newValue || '' })}
                renderInput={(params) => (
                  <TextField {...params} label="Department" required />
                )}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Designation"
                placeholder="Professor, Lecturer, etc."
                value={formData.designation || ''}
                onChange={(e) => setFormData({ ...formData, designation: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <Autocomplete
                multiple
                freeSolo
                options={[]}
                value={formData.subjects || []}
                onChange={(_, newValue) => setFormData({ ...formData, subjects: newValue })}
                renderInput={(params) => (
                  <TextField {...params} label="Subjects" placeholder="Type and press Enter" />
                )}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Qualification"
                placeholder="PhD, M.Sc., B.Tech., etc."
                value={formData.qualification || ''}
                onChange={(e) => setFormData({ ...formData, qualification: e.target.value })}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Specialization"
                placeholder="Area of expertise"
                value={formData.specialization || ''}
                onChange={(e) => setFormData({ ...formData, specialization: e.target.value })}
              />
            </Grid>

            {/* Office Information */}
            <Grid item xs={12}>
              <Typography variant="subtitle2" color="primary" gutterBottom sx={{ mt: 2 }}>
                Office Information
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Office Room"
                placeholder="e.g., CSE-301"
                value={formData.office_room || ''}
                onChange={(e) => setFormData({ ...formData, office_room: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Office Hours"
                placeholder="e.g., Mon-Wed 2-4 PM"
                value={formData.office_hours || ''}
                onChange={(e) => setFormData({ ...formData, office_hours: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Joining Date"
                type="date"
                InputLabelProps={{ shrink: true }}
                value={formData.joining_date?.split('T')[0] || ''}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    joining_date: e.target.value ? new Date(e.target.value).toISOString() : undefined,
                  })
                }
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Photo URL"
                placeholder="https://..."
                value={formData.photo_url || ''}
                onChange={(e) => setFormData({ ...formData, photo_url: e.target.value })}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                multiline
                rows={3}
                label="Bio"
                placeholder="Short biography..."
                value={formData.bio || ''}
                onChange={(e) => setFormData({ ...formData, bio: e.target.value })}
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Cancel</Button>
          <Button onClick={handleSave} variant="contained">
            {editingTeacher ? 'Update' : 'Create'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar */}
      <Snackbar
        open={snackbar.open}
        message={snackbar.message}
        severity={snackbar.severity}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
      />
    </Container>
  );
};

export default TeachersPage;
