name: Database Maintenance

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    name: Run Database Cleanup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Clean up old user activity
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          echo "Cleaning up old user activity..."
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/cleanup_old_user_activity" \
            -H "apikey: $SUPABASE_SERVICE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "Content-Type: application/json"
      
      - name: Clean up expired notices
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          echo "Cleaning up expired notices..."
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/cleanup_expired_notices" \
            -H "apikey: $SUPABASE_SERVICE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "Content-Type: application/json"
      
      - name: Clean up old read messages
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          echo "Cleaning up old read messages..."
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/cleanup_old_read_messages" \
            -H "apikey: $SUPABASE_SERVICE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "Content-Type: application/json"
      
      - name: Cleanup summary
        run: |
          echo "✅ Database cleanup completed successfully"
          echo "- Old user activity cleaned (90+ days)"
          echo "- Expired notices deactivated"
          echo "- Old read messages cleaned (30+ days)"

  refresh-views:
    name: Refresh Materialized Views
    runs-on: ubuntu-latest
    needs: cleanup
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Refresh notice summary view
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          echo "Refreshing materialized views..."
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/refresh_notice_summary" \
            -H "apikey: $SUPABASE_SERVICE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "Content-Type: application/json"
      
      - name: Views refresh summary
        run: |
          echo "✅ Materialized views refreshed successfully"
